#' Downloads and formats nClimGrid monthly data
#'
#' @param year Year, YYYY format
#' @param measurement Measurement type (i.e. "tave", "tmax", "tmin", "prcp")
#' @param region Region (i.e. "conus", "ak")
#' @param wide Convert to wide format, default is FALSE
#' @param verbose Verbose, default is FALSE
#'
#' @return Data frame
#'
#' @importFrom dplyr mutate mutate_all
#' @importFrom tidyr pivot_longer
#' @importFrom magrittr %<>% %>% set_names
#' @importFrom glue glue
get_nclimgrid_monthly <- function(year, measurement = "tave", region = "conus", wide = FALSE, verbose = FALSE) {

  #validates inputs and stops if not valid
  progress_msg(verbose, "Validating inputs...")

  validate_year(year)
  validate_region(region)
  validate_measurement(measurement)

  #build url, download data and convert units
  #column count and names may vary depending when the last month was published, they are numerically named here
  #units are converted from C to F and mm to in as default to match normals data standard
  progress_msg(verbose, "Fetching data from NOAA...")

  noaa_url <- glue('https://www.ncei.noaa.gov/pub/data/cirs/climgrid/{year}.{measurement}.{region}.pnt')

  nclim_data <- noaa_url %>%
    read.delim(sep = "", header = FALSE) %>%
    set_names(c("lat", "long", 1:(ncol(.)-2))) %>%
    mutate_at(3:ncol(.), standardize_units, measurement)

  #return as is or convert to long format (default option)
  if (!wide) {

    progress_msg(verbose, "Converting to long format...")

    nclim_data %<>%
      pivot_longer(names_to = "month", values_to = "value", -c("lat", "long")) %>%
      mutate(month = factor(month, levels = 1:12))

  }

  #store metadata as attributes to the data frame
  attr(nclim_data, "year") <- year
  attr(nclim_data, "measurement") <- measurement
  attr(nclim_data, "region") <- region
  attr(nclim_data, "unit") <- ifelse(grepl("^t", measurement), "Fahrenheit", "inches")
  attr(nclim_data, "wide") <- wide
  attr(nclim_data, "anomaly_df") <- FALSE

  #finish and return
  progress_msg(verbose, "Done.")

  return(nclim_data)

}

#' Downloads and formats nClimGrid normals data
#'
#' Normals data exist only for predefined periods. To see valid start and end of periods of record, see \code{validate_normals_period()}
#'
#' @param period Normals period. (i.e. "1901-2000" , "1981-2010", "1991-2020", "2006-2020"). Defaults to "1901-2000" (20th Century)
#' @param measurement Measurement type (i.e. "tave", "tmax", "tmin", "prcp")
#' @param region Region (i.e. "conus", "ak")
#' @param wide Convert to wide format, default is FALSE
#' @param verbose Verbose, default is FALSE
#'
#' @return Data frame
#'
#' @importFrom dplyr mutate mutate_all
#' @importFrom tidyr pivot_longer
#' @importFrom magrittr %<>% %>% set_names
#' @importFrom glue glue
get_nclimgrid_normals <- function(period = "1901-2000", measurement = "tave", region = "conus", wide = FALSE, verbose = FALSE) {

  #validates inputs and stops if not valid
  progress_msg(verbose, "Validating inputs...")

  validate_normals_period(period)
  validate_region(region)
  validate_measurement(measurement)

  #build url, download data and convert units
  #file names for normals use "us" for "conus"
  #column count is fixed with 12 months of data
  progress_msg(verbose, "Fetching normals data from NOAA...")

  noaa_url <- glue('https://www.ncei.noaa.gov/pub/data/cirs/climgrid/normals/{region}_{measurement}_{period}_normal.dat',
                   region = ifelse(region == "conus", "us", "ak"))

  nclim_data <- noaa_url %>%
    read.delim(sep = "", header = FALSE) %>%
    set_names(c("lat", "long", 1:12))

  #return as is or convert to long format (default option)
  if (!wide) {

    progress_msg(verbose, "Converting to long format...")

    nclim_data %<>%
      pivot_longer(names_to = "month", values_to = "value", -c("lat", "long")) %>%
      mutate(month = factor(month, levels = 1:12))

  }

  #store metadata as attributes to the data frame
  attr(nclim_data, "period") <- period
  attr(nclim_data, "measurement") <- measurement
  attr(nclim_data, "region") <- region
  attr(nclim_data, "unit") <- ifelse(grepl("^t", measurement), "Fahrenheit", "inches")
  attr(nclim_data, "wide") <- wide
  attr(nclim_data, "anomaly_df") <- FALSE

  #finish and return
  progress_msg(verbose, "Done.")

  return(nclim_data)

}


#' Compute anomaly between two datasets
#'
#' The anomaly is computed by subtracting the values in dataset "b" from dataset "a".
#' Only the months in dataset "a" are kept if not available in dataset "b".
#'
#' @param nclimgrid_data_a Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#' @param nclimgrid_data_b Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#'
#' @return Data frame with anomaly. Attributes are inherited from dataset "a".
#'
#' @importFrom dplyr mutate select left_join
#' @importFrom magrittr %>% %<>% subtract
#'
#' @export
compute_anomaly <- function(nclimgrid_data_a, nclimgrid_data_b) {

  #validate that both data frames are similar
  if (attr(nclimgrid_data_a, "wide") != attr(nclimgrid_data_b, "wide")) {

    stop("Both datasets need to be in the same format, either wide or long.")

  }

  if (attr(nclimgrid_data_a, "measurement") != attr(nclimgrid_data_b, "measurement")) {

    stop("Both datasets need to have the same measurement type to compute the anomaly (i.e. tave, tmin, tmax, prcp)")

  }

  if (attr(nclimgrid_data_a, "region") != attr(nclimgrid_data_b, "region")) {

    stop("Both datasets must be for the same region.")

  }


  #compute delta in wide format or long format
  if (attr(nclimgrid_data_a, "wide")) {

    #pixel counts must match, this error is unlikely to occur
    if (nrow(nclimgrid_data_a) != nrow(nclimgrid_data_b)) { stop("Number of coordinate pairs differ between monthly and normals data.") }

    #build a new data frame with lat long and same columns available in monthly (which may be less months than normals)
    anomaly <- nclimgrid_data_a %>%
      select(lat, long) %>%
      cbind(nclimgrid_data_a %>%
              select(-lat, -long) %>%
              subtract(nclimgrid_data_b %>% select(names(nclimgrid_data_a), -lat, -long)))

  } else {

    anomaly <- nclimgrid_data_a %>%
      left_join(nclimgrid_data_b, by = c("lat", "long", 'month')) %>%
      mutate(value = value.x - value.y) %>%
      select(-contains("value."))

  }

  #set attributes of the data frame based on the inputs
  attr(anomaly, "year") <- attr(nclimgrid_data_a, "year")
  attr(anomaly, "measurement") <- attr(nclimgrid_data_a, "measurement")
  attr(anomaly, "region") <- attr(nclimgrid_data_a, "region")
  attr(anomaly, "unit") <- attr(nclimgrid_data_a, "unit")
  attr(anomaly, "wide") <- attr(nclimgrid_data_a, "wide")
  attr(anomaly, "anomaly_df") <- TRUE

  return(anomaly)

}


