#' Plot absolute measurement values
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by get_nclimgrid_monthly() or get_nclimgrid_normals()
#' @param subset_months List of numeric months to include, defaults to all (1:12)
#' @param show_states Show state outlines, default is TRUE
#' @param show_counties Show county outlines, default is FALSE
#' @param facet_cols Number of cols for faceting months, defaults to 2
#' @param title Optional plot title. A default plot title is generated based on the data type in nclimgrid_data
#' @param subtitle  Optional plot title. A default plot title is generated based on the data type in nclimgrid_data
#' @param show_credit Show caption with dataset credit to NOAA, default is TRUE
#'
#' @return Returns a ggplot object
#'
#' @import ggplot2
#' @importFrom maps map_data
plot_measurement_data <- function(nclim_data,
                                  subset_months = 1:12,
                                  show_states = TRUE,
                                  show_counties = FALSE,
                                  facet_cols = 2,
                                  title = NULL,
                                  subtitle = NULL,
                                  show_credit = TRUE) {

  #stop if format of nclim_data is not long
  #TODO: convert here on the fly if wide
  if (attr(nclim_data, "wide") == TRUE) { stop("Plotting only available for data loaded in long format") }

  #stop if data passed in as a anomaly df
  if (attr(nclim_data, "anomaly_df") == TRUE) { stop("Use plot_anomaly_data() for computed nClimGrid anomaly data frames.")}

  #get bin breaks and color scales
  color_scales <- define_color_scale(measurement = attr(nclim_data, "measurement"), anomaly = FALSE)

  #optional states and county outlines
  #TODO: add Alaska outline if region=='ak'
  state_outlines <- county_outlines <- NULL

  if (show_states) {
    state_outlines <- geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group), color = "black", fill=NA, size=0.1)
  }

  if (show_counties) {
    county_outlines <- geom_polygon(data = map_data("county"), aes(x = long, y = lat, group = group), color = "gray60", fill=NA, size=0.1)
  }

  #if this data needs to be binned, convert value column to bins
  if (!is.na(color_scales$breaks)) {
    nclim_data %<>% mutate(value = cut(value, breaks = color_scales$breaks, include.lowest = TRUE))
  }

  #generate plot object
  plot_object <- nclim_data %>%
    filter(month %in% subset_months) %>%
    ggplot() +
    geom_raster(aes(x = long, y = lat, fill = value)) +
    scale_fill_distiller(palette = "RdYlBu", name = "°F") +
    facet_wrap(~ month, ncol = facet_cols,
               labeller = labeller(month = month_to_name)) +
    coord_cartesian() +
    theme(legend.position = "right") +
    theme_minimal() +
    labs(title = title,
         subtitle = subtitle,
         caption = ifelse(show_credit, "Source: NOAA Monthly U.S. Climate Gridded Dataset (NClimGrid)", ""),
         x = NULL,
         y = NULL) +
    state_outlines +
    county_outlines

  return(plot_object)

}

#' Define bins breaks and color scales to closely match NOAA's standard plots
#'
#' @param measurement Measurement type (i.e. tave, tmax, tmin, prcp)
#' @param anomaly TRUE for anomaly from normals color scale, FALSE for absolute measurement data
#'
#' @importFrom tibble tribble
#' @importFrom RColorBrewer brewer.pal col
define_color_scale <- function(measurement, anomaly = FALSE) {

  #validate measurement
  validate_measurement(measurement)

  #predefined breaks and color scales
  if (anomaly == FALSE) {

    #these are the breaks for binning absolute measurements
    plot_scales <- tribble(
      ~measurement_, ~breaks, ~color_scale,
      "tave",   NA, NA,
      "tmax",   NA, NA,
      "tmin",   NA, NA,
      "prcp",  c(0, 0.1, 0.5, 1, 2, 4, 6, 8, 10, 12, 15, 20, Inf), colorRampPalette(brewer.pal(8, "BrBG"))(13)
    )

  } else {

    temp_anomaly_colors <- colorRampPalette(brewer.pal(11, "RdBu"))(12)
    temp_anomaly_colors[6:7] <- "#FDFDFD"

    #these are the breaks for binning anomalies
    plot_scales <- tribble(
      ~measurement_, ~breaks, ~color_scale,
      "tave",   c(-Inf,seq(-15,15, by=3), Inf), temp_anomaly_colors,
      "tmax",   c(-Inf,seq(-15,15, by=3), Inf), temp_anomaly_colors,
      "tmin",   c(-Inf,seq(-15,15, by=3), Inf), temp_anomaly_colors,
      "prcp",  c(-Inf,seq(-10,10, by=2),Inf), c(brewer.pal(10, "BrBG")[1:5], "#FDFDFD", "#FDFDFD", brewer.pal(10, "BrBG")[6:10]) #set the values near 0 to near-white
    )

  }

  #return as a name list
  plot_scales %>%
    filter(measurement_ == measurement) %>%
    select(breaks, color_scale) %>%
    as.list %>%
    lapply(unlist)


}


#' Based on attributes of the nclim_data data frame, generate a default title and subtitle for the plots
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by get_nclimgrid_monthly() or get_nclimgrid_normals()
#'
#' @return List with $title and $subtitle
plot_title_builder <- function(nclimgrid_data) {

  return("")

}


#' Plot distribution comparison
#'
#' For a list of nClimGrid data frames, plot the distributions. Option to facet and subset by month
#'
plot_measurement_distributions <- function(nclimgrid_df_list,
                                           subset_months = 1:12,
                                           facet_cols = 2) {

  #get labels for each data frame in list
  #check if wide or long
  #check if same measurement type (at least must be temp or prcp)
  #check if anomaly or not, must be same to be comparable
  #stack dfs, append labels from previous step as a column

  #one measurement
  #m_tave %>% ggplot() + geom_histogram(aes(x=value, fill=..x..)) + facet_wrap(~month, labeller = labeller(month = month_to_name)) + scale_fill_distiller(palette = "RdYlBu", name = "°F") + theme_minimal()

  #mirror plot with two measuremts
  # ggplot() + geom_histogram(data = m_tave, aes(x=value, y=..density.., fill=..x..), bins = 50) + geom_histogram(data = n_tave, aes(x=value, y=-..density.., fill=..x..), bins = 50) + facet_wrap(~month, labeller = labeller(month = month_to_name)) + scale_fill_distiller(palette = "RdYlBu", name = "°F") + theme_minimal() + coord_flip() + geom_hline(yintercept=0, col='white') + labs(title = "normal (left) vs measurement (right)")
}
