#' Plot absolute measurement values
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#' @param show_states Show state outlines, default is TRUE
#' @param show_counties Show county outlines, default is FALSE
#' @param facet_cols Number of cols for faceting months, defaults to 2
#' @param show_credit Show caption with dataset credit to NOAA, default is TRUE
#'
#' @return Returns a ggplot object
#'
#' @import ggplot2
#' @importFrom magrittr %>%
plot_nclimgrid <- function(nclimgrid_data,
                           show_states = TRUE,
                           show_counties = FALSE,
                           facet_cols = 2,
                           show_credit = TRUE) {

  #stop if format of nclimgrid_data is not long
  #TODO: convert here on the fly if wide
  if (attr(nclimgrid_data, "wide") == TRUE) {
    stop("Plotting only available for data loaded in long format.")
  }

  #check for column names
  if (!all(c("lat", "long", "month", "value") %in% names(nclimgrid_data))) {
    stop("Input data frame must have 'lat', 'long', 'month' and 'value' columns.")
  }

  #get bin breaks and color scales
  color_scales <- define_color_scale(nclimgrid_data)

  #build the title based on the data
  plot_titles <- plot_title_builder(nclimgrid_data)

  #if this data needs to be binned, convert value column to bins
  if (!is.null(color_scales$breaks)) {
    nclimgrid_data %<>% mutate(value = cut(value, breaks = color_scales$breaks, include.lowest = TRUE))
  }

  #optional states and county outlines.
  #TODO: add Alaska outline if region=='ak'
  state_outlines <- county_outlines <- NULL

  if (show_states) {
    state_outlines <- geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group), color = "black", fill=NA, size=0.1)
  } else {
    state_outlines <- geom_polygon(data = map_data("usa"), aes(x = long, y = lat, group = group), color = "black", fill=NA, size=0.1)
  }

  if (show_counties) {
    county_outlines <- geom_polygon(data = map_data("county"), aes(x = long, y = lat, group = group), color = "gray60", fill=NA, size=0.1)
  }

  #generate plot object
  plot_object <- nclimgrid_data %>%
    ggplot() +
    geom_raster(aes(x = long, y = lat, fill = value)) +
    facet_wrap(~ month, ncol = facet_cols,
               labeller = labeller(month = month_to_name)) +
    coord_cartesian() +
    theme(legend.position = "right") +
    theme_minimal() +
    color_scales$fill +
    labs(title = plot_titles$title,
         subtitle = plot_titles$subtitle,
         caption = ifelse(show_credit, "Source: NOAA Monthly U.S. Climate Gridded Dataset (NClimGrid)", ""),
         x = NULL,
         y = NULL) +
    state_outlines +
    county_outlines

  return(plot_object)

}

#' Define bins breaks and color scales to closely match NOAA's standard plots
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#'
#' @importFrom tibble tribble
#' @importFrom RColorBrewer brewer.pal
define_color_scale <- function(nclimgrid_data) {

  measurement <- attr(nclimgrid_data, "measurement")
  anomaly <- attr(nclimgrid_data, "anomaly_df")

  #validate measurement
  validate_measurement(measurement)

  #predefined breaks and color scales for monthly values
  if (anomaly == FALSE) {

    if (measurement == "prcp") {

      return(list(breaks = c(0, 0.1, 0.5, 1, 2, 4, 6, 8, 10, 12, 15, 20, Inf),
                  fill = scale_fill_manual(values = colorRampPalette(brewer.pal(8, "BrBG"))(13),
                                           drop = FALSE,
                                           name = "in."),
                  histogram_colors = scale_fill_distiller(palette = "BrBG",
                                                          direction = 1,
                                                          name = "in.")))

    } else {

      return(list(breaks = NULL,
                  fill = scale_fill_distiller(palette = "RdYlBu",
                                              name = "°F"),
                  histogram_colors = scale_fill_distiller(palette = "RdYlBu",
                                                          direction = -1,
                                                          name = "°F")))

    }

  }

  #predefined breaks and color scales for anomaly data frames
  if (anomaly == TRUE) {

    if (measurement == "prcp") {

      prcp_anomaly_colors <- c(brewer.pal(10, "BrBG")[1:5], "#FDFDFD", "#FDFDFD", brewer.pal(10, "BrBG")[6:10])

      return(list(breaks = c(-Inf,seq(-10, 10, by=2),Inf),
                  fill = scale_fill_manual(values = prcp_anomaly_colors,
                                           drop = FALSE,
                                           name = "in."),
                  histogram_colors = scale_fill_distiller(palette = "BrBG",
                                                          type = "div",
                                                          direction = 1,
                                                          name = "in.")))

    } else {

      temp_anomaly_colors <- colorRampPalette(brewer.pal(11, "RdBu"))(12)
      temp_anomaly_colors[6:7] <- "#FDFDFD"

      return(list(breaks = c(-Inf,seq(-15, 15, by=3), Inf),
                  fill = scale_fill_manual(values = rev(temp_anomaly_colors),
                                           drop = FALSE,
                                           name = "°F"),
                  histogram_colors = scale_fill_distiller(palette = "RdYlBu",
                                                          type = "div",
                                                          direction = -1,
                                                          name = "°F")))

    }

  }

}


#' Based on attributes of the nclimgrid_data data frame, generate a default title and subtitle for the plots.
#'
#' The default title and subtitle can be overriden by adding \code{ggplot2::labs(title = "", subtitle = "")} to the plot object
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#'
#' @importFrom glue glue
#' @importFrom magrittr %>%
#' @importFrom dplyr case_when
#' @return List with $title and $subtitle
plot_title_builder <- function(nclimgrid_data) {

  anomaly_ <- attr(nclimgrid_data, "anomaly_df") %>% ifelse(., "Anomaly","")
  period_ <- attr(nclimgrid_data, "period")

  m_ <- attr(nclimgrid_data, "measurement")
  measurement_ <- case_when(m_ == "prcp" ~ "Precipitation",
                            m_ == "tmax" ~ "Maximum Temperatures",
                            m_ == "tave" ~ "Average Temperatures",
                            m_ == "tmin" ~ "Minimum Temperatures",
                            TRUE ~ "") %>%
    #remove plural from temperature for anomaly plots
    ifelse(anomaly_ == "Anomaly", gsub("res", "re", .), .)



  #if nclimgrid_data contains normals, the year string is replaced by "Normal"
  #the reference period appears as a subtitle the period is displayed
  year_ <- attr(nclimgrid_data, "year") %>% ifelse(is.null(period_), ., "Normal")


  list(title = glue("{year_} {measurement_} {anomaly_}"),
       subtitle = ifelse(!is.null(period_), glue("Reference Period: {period_}"), ""))

}


#' Plot distribution
#'
#' @param nclimgrid_data_a Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#' @param nclimgrid_data_b (Optional) Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#' @param facet_cols Number of cols for faceting months, defaults to 2
#' @param show_credit Show caption with dataset credit to NOAA, default is TRUE
#'
#' @import ggplot2
#' @importFrom magrittr %>%
#' @importFrom scales percent
#'
#' @export
plot_nclimgrid_histogram <- function(nclimgrid_data_a,
                                     nclimgrid_data_b = NULL,
                                     facet_cols = 3,
                                     show_credit = TRUE) {

  #stop if format of nclimgrid_data is not long
  #TODO: convert here on the fly if wide
  if (attr(nclimgrid_data_a, "wide") == TRUE) {
    stop("Plotting only available for data loaded in long format.")
  }

  #check for column names
  if (!all(c("month", "value") %in% names(nclimgrid_data_a))) {
    stop("Input data frame must have 'month' and 'value' columns.")
  }

  #get bin breaks and color scales
  color_scales <- define_color_scale(nclimgrid_data_a)

  #build the title based on the data
  plot_titles_a <- plot_title_builder(nclimgrid_data_a)

  histogram_plot <- nclimgrid_data_a %>%
    ggplot() +
    geom_histogram(aes(x=value, y=..density.., fill=..x..), bins = 30) +
    facet_wrap(~month, ncol = facet_cols, labeller = labeller(month = month_to_name)) +
    color_scales$histogram_colors +
    theme_minimal() +
    labs(title = plot_titles_a$title,
         subtitle = plot_titles_a$subtitle,
         caption = ifelse(show_credit, "Source: NOAA Monthly U.S. Climate Gridded Dataset (NClimGrid)", ""),
         x = NULL,
         y = NULL) +
    scale_y_continuous(label = scales::percent)

  #adding a mirrored histogram for nclimgrid_data_b if present
  if (!is.null(nclimgrid_data_b)) {

    #stop if format of nclimgrid_data is not long
    #TODO: convert here on the fly if wide
    if (attr(nclimgrid_data_b, "wide") == TRUE) {
      stop("Plotting only available for data loaded in long format.")
    }

    #check for column names
    if (!all(c("month", "value") %in% names(nclimgrid_data_b))) {
      stop("Input data frame must have 'month' and 'value' columns.")
    }

    #data b must be of same type (temperature or preciptation as a)
    if (grepl("^p", attr(nclimgrid_data_a, "measurement")) != grepl("^p", attr(nclimgrid_data_b, "measurement"))) {
      stop("Both datasets must be of the same measurement type (either temperatures or precipitation)")
    }

    #build the title based on the data
    plot_titles_b <- plot_title_builder(nclimgrid_data_b)

    #add the elements to the plot but mirrored, flip and adjust title
    histogram_plot <- histogram_plot +
      geom_histogram(data = nclimgrid_data_b, aes(x=value, y=-..density.., fill=..x..), bins = 30) +
      coord_flip() +
      geom_hline(yintercept=0, col='white') +
      labs(title = paste0(plot_titles_b$title, "(left) vs ", plot_titles_a$title, "(right)"),
           subtitle = paste(plot_titles_b$subtitle, plot_titles_a$subtitle))

  }

  return(histogram_plot)

}
