#' Plot absolute measurement values
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#' @param show_states Show state outlines, default is TRUE
#' @param show_counties Show county outlines, default is FALSE
#' @param facet_cols Number of cols for faceting months, defaults to 2
#' @param show_credit Show caption with dataset credit to NOAA, default is TRUE
#'
#' @return Returns a ggplot object
#'
#' @import ggplot2
#' @importFrom magrittr %>%
plot_nclimgrid <- function(nclimgrid_data,
                           show_states = TRUE,
                           show_counties = FALSE,
                           facet_cols = 2,
                           show_credit = TRUE) {

  #stop if format of nclimgrid_data is not long
  #TODO: convert here on the fly if wide
  if (attr(nclimgrid_data, "wide") == TRUE) { stop("Plotting only available for data loaded in long format.") }

  #check for column names
  if (!all(c("lat", "long", "month", "value") %in% names(nclimgrid_data))) {
    stop("Input data frame must have 'lat', 'long', 'month' and 'value' columns.")
  }

  #get bin breaks and color scales
  color_scales <- define_color_scale(nclimgrid_data)

  #build the title based on the data
  plot_titles <- plot_title_builder(nclimgrid_data)

  #if this data needs to be binned, convert value column to bins
  if (!is.null(color_scales$breaks)) {
    nclimgrid_data %<>% mutate(value = cut(value, breaks = color_scales$breaks, include.lowest = TRUE))
  }

  #optional states and county outlines.
  #TODO: add Alaska outline if region=='ak'
  state_outlines <- county_outlines <- NULL

  if (show_states) {
    state_outlines <- geom_polygon(data = map_data("state"), aes(x = long, y = lat, group = group), color = "black", fill=NA, size=0.1)
  } else {
    state_outlines <- geom_polygon(data = map_data("usa"), aes(x = long, y = lat, group = group), color = "black", fill=NA, size=0.1)
  }

  if (show_counties) {
    county_outlines <- geom_polygon(data = map_data("county"), aes(x = long, y = lat, group = group), color = "gray60", fill=NA, size=0.1)
  }

  #generate plot object
  plot_object <- nclimgrid_data %>%
    ggplot() +
    geom_raster(aes(x = long, y = lat, fill = value)) +
    facet_wrap(~ month, ncol = facet_cols,
               labeller = labeller(month = month_to_name)) +
    coord_cartesian() +
    theme(legend.position = "right") +
    theme_minimal() +
    color_scales$fill +
    labs(title = plot_titles$title,
         subtitle = plot_titles$subtitle,
         caption = ifelse(show_credit, "Source: NOAA Monthly U.S. Climate Gridded Dataset (NClimGrid)", ""),
         x = NULL,
         y = NULL) +
    state_outlines +
    county_outlines

  return(plot_object)

}

#' Define bins breaks and color scales to closely match NOAA's standard plots
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#'
#' @importFrom tibble tribble
#' @importFrom RColorBrewer brewer.pal
define_color_scale <- function(nclimgrid_data) {

  measurement <- attr(nclimgrid_data, "measurement")
  anomaly <- attr(nclimgrid_data, "anomaly_df")

  #validate measurement
  validate_measurement(measurement)

  #predefined breaks and color scales for monthly values
  if (anomaly == FALSE) {

    if (measurement == "prcp") {

      return(list(breaks = c(0, 0.1, 0.5, 1, 2, 4, 6, 8, 10, 12, 15, 20, Inf),
                  fill = scale_fill_manual(values = colorRampPalette(brewer.pal(8, "BrBG"))(13),
                                           drop = FALSE,
                                           name = "in.")))

    } else {

      return(list(breaks = NULL,
                  fill = scale_fill_distiller(palette = "RdYlBu",
                                              name = "°F")))

    }

  }

  #predefined breaks and color scales for anomaly data frames
  if (anomaly == TRUE) {

    if (measurement == "prcp") {

      prcp_anomaly_colors <- c(brewer.pal(10, "BrBG")[1:5], "#FDFDFD", "#FDFDFD", brewer.pal(10, "BrBG")[6:10])

      return(list(breaks = c(-Inf,seq(-10, 10, by=2),Inf),
                  fill = scale_fill_manual(values = prcp_anomaly_colors,
                                           drop = FALSE,
                                           name = "in.")))

    } else {

      temp_anomaly_colors <- colorRampPalette(brewer.pal(11, "RdBu"))(12)
      temp_anomaly_colors[6:7] <- "#FDFDFD"

      return(list(breaks = c(-Inf,seq(-15, 15, by=3), Inf),
                  fill = scale_fill_manual(values = rev(temp_anomaly_colors),
                                           drop = FALSE,
                                           name = "°F")))

    }

  }

}


#' Based on attributes of the nclimgrid_data data frame, generate a default title and subtitle for the plots.
#'
#' The default title and subtitle can be overriden by adding \code{ggplot2::labs(title = "", subtitle = "")} to the plot object
#'
#' @param nclimgrid_data Data frame with nClimGrid data, generated by \code{get_nclimgrid_monthly()} or \code{get_nclimgrid_normals()}
#'
#' @importFrom glue glue
#' @importFrom magrittr %>%
#' @importFrom dplyr case_when
#' @return List with $title and $subtitle
plot_title_builder <- function(nclimgrid_data) {

  anomaly_ <- attr(nclimgrid_data, "anomaly_df") %>% ifelse(., "Anomaly","")
  period_ <- attr(nclimgrid_data, "period")

  m_ <- attr(nclimgrid_data, "measurement")
  measurement_ <- case_when(m_ == "prcp" ~ "Precipitation",
                           m_ == "tmax" ~ "Maximum Temperatures",
                           m_ == "tave" ~ "Average Temperatures",
                           m_ == "tmin" ~ "Minimum Temperatures",
                           TRUE ~ "") %>%
    #remove plural from temperature for anomaly plots
    ifelse(anomaly_ == "Anomaly", gsub("res", "re", .), .)



  #if nclimgrid_data contains normals, the year string is replaced by "Normal"
  #the reference period appears as a subtitle the period is displayed
  year_ <- attr(nclimgrid_data, "year") %>% ifelse(is.null(period_), ., "Normal")


  list(title = glue("{year_} {measurement_} {anomaly_}"),
       subtitle = ifelse(!is.null(period_), glue("Reference Period: {period_}"), ""))

}


#' Plot distribution comparison
#'
#' For a list of nClimGrid data frames, plot the distributions
#'
plot_nclimgrid_histogram <- function(nclimgrid_data,
                                     ...,
                                     facet_cols = 2) {

  #get labels for each data frame in list
  #check if wide or long
  #check if same measurement type (at least must be temp or prcp)
  #check if anomaly or not, must be same to be comparable
  #stack dfs, append labels from previous step as a column

  #one measurement
  #m_tave %>% ggplot() + geom_histogram(aes(x=value, fill=..x..)) + facet_wrap(~month, labeller = labeller(month = month_to_name)) + scale_fill_distiller(palette = "RdYlBu", name = "°F") + theme_minimal()

  #mirror plot with two measuremts
  # ggplot() + geom_histogram(data = m_tave, aes(x=value, y=..density.., fill=..x..), bins = 50) + geom_histogram(data = n_tave, aes(x=value, y=-..density.., fill=..x..), bins = 50) + facet_wrap(~month, labeller = labeller(month = month_to_name)) + scale_fill_distiller(palette = "RdYlBu", name = "°F") + theme_minimal() + coord_flip() + geom_hline(yintercept=0, col='white') + labs(title = "normal (left) vs measurement (right)")
}
